import { HandPort } from '../port/HandPort.js';
import {
  ALL_OPS, FIX_TOOLS, FIX_PREFIX, DOC_PROPERTY_KEY, refuse, str, num, int, bool, arr, need, hex, span, envelope, clip, nowEpoch, fieldPieces, BUILTIN_PARAGRAPH_STYLES,
} from './handCore.js';

/**
 * 가짜 손 — 메모리 문서(ui/docFixture.js 꼴) 위에서 도구 44개를 **정말로** 돌린다. Word 없이 흐름을 끝까지 재는 자리이고,
 * 진짜 손(WordHand)과 같은 봉투·같은 거절을 낸다. 지어내는 것은 없다 — Word 만 아는 것(요구 집합, OOXML)은 「모른다」로.
 */
export class FakeHand extends HandPort {
  constructor(model, { document = 'doc-fake', label = 'fake.docx', supports } = {}) {
    super();
    this.model = model;
    this.model.paragraphs ??= []; this.model.tables ??= []; this.model.comments ??= []; this.model.bookmarks ??= {}; this.model.settings ??= {}; this.model.tags ??= {};
    this.model.properties ??= {}; this.model.trackChanges ??= 'Off'; this.model.changes ??= []; this.model.headers ??= [{ header: '', footer: '' }]; this.model.notes ??= []; this.model.styleDefs ??= {};
    this.supports = supports ?? (() => true);
    this.document = document; this.labelText = label;
    this.epoch = nowEpoch(); this.count = 0; this.snapshots = new Map(); this.nextComment = 1;
  }
  get label() { return this.labelText; }
  #mutated() { this.count += 1; if (this.model.trackChanges !== 'Off') this.model.changes.push({ type: 'Edit', author: 'magi', date: new Date().toISOString(), text: '' }); }
  #env(result, changed = []) { const out = envelope(this, result, changed); if (changed.length) out.result.now = { paragraphs: this.model.paragraphs.length }; return out; }
  #need(name, version, what) { if (!this.supports(name, version)) refuse(`${what} 은 ${name} ${version} 이 필요한데 이 호스트에는 없습니다`); }
  get P() { return this.model.paragraphs; }
  #pick(a, opts) { const s = span(a, this.P.length, opts); return { ...s, list: this.P.slice(s.from - 1, s.to) }; }
  #anchor(a) {
    const after = int(a, 'after'); const before = int(a, 'before'); const at = str(a, 'at');
    if (after != null) { if (after < 1 || after > this.P.length) refuse(`문서에 ${after}번 문단이 없습니다 — 문단 ${this.P.length}개`); return { index: after, said: `문단 ${after} 뒤에` }; }
    if (before != null) { if (before < 1 || before > this.P.length) refuse(`문서에 ${before}번 문단이 없습니다 — 문단 ${this.P.length}개`); return { index: before - 1, said: `문단 ${before} 앞에` }; }
    if (at === 'start') return { index: 0, said: '본문 처음에' };
    return { index: this.P.length, said: '본문 끝에' };
  }
  #shift(from, delta) { for (const t of this.model.tables) if (t.after >= from) t.after += delta; for (const c of this.model.comments) if (c.paragraph >= from) c.paragraph += delta; }
  #table(a) { const n = int(a, 'table') ?? refuse('table 이 없습니다 — 표 번호(1부터)'); const ts = [...this.model.tables].sort((x, y) => x.after - y.after); if (n < 1 || n > ts.length) refuse(`문서에 ${n}번 표가 없습니다 — 표 ${ts.length}개`); return { t: ts[n - 1], n }; }
  #targets(a) {
    const { from, to, list } = this.#pick(a); const text = str(a, 'text');
    if (!text) return { from, to, hits: list.map((p, i) => ({ p, i: from + i })), said: `문단 ${from}${to > from ? `–${to}` : ''}` };
    const hits = []; list.forEach((p, i) => { let at = p.text.indexOf(text); while (at >= 0) { hits.push({ p, i: from + i, at }); at = p.text.indexOf(text, at + text.length); } });
    if (!hits.length) refuse(`문단 ${from}${to > from ? `–${to}` : ''} 에 「${clip(text, 40)}」 가 없습니다`);
    return { from, to, hits, said: `문단 ${from}${to > from ? `–${to}` : ''} 의 「${clip(text, 30)}」 ${hits.length}곳` };
  }

  async run(op, a = {}) {
    if (!ALL_OPS.includes(op)) refuse(`모르는 조작입니다: ${op} — 아는 것: ${ALL_OPS.join(', ')}`);
    switch (op) {
      case 'list_paragraphs': { const max = int(a, 'max') ?? 200; const { from } = this.#pick(a, { must: false }); const to = int(a, 'to') == null ? this.P.length : this.#pick(a, { must: false }).to; const rows = []; // 목차는 from 만 주면 끝까지 넘긴다
        for (let i = from - 1; i < to && rows.length < max; i += 1) { const p = this.P[i]; rows.push({ paragraph: i + 1, style: p.style ?? 'Normal', builtin: (p.style ?? 'Normal').replace(/\s+/g, ''), text: clip(p.text, 80), list: p.list ? { level: p.list.level ?? 0, mark: p.list.kind === 'numbered' ? '1.' : '•' } : null }); }
        return this.#env({ paragraphs: rows, from, to: Math.min(to, from - 1 + rows.length), total: this.P.length, tables: this.model.tables.length, truncated: rows.length < to - from + 1 }); }
      case 'read_paragraphs': { const maxChars = int(a, 'max_chars') ?? 4000; const { from, to, list } = this.#pick(a, { must: false });
        return this.#env({ paragraphs: list.map((p, i) => ({ paragraph: from + i, style: p.style ?? 'Normal', builtin: (p.style ?? 'Normal').replace(/\s+/g, ''), align: p.align ?? 'Left', list: p.list ? true : undefined, text: p.text.slice(0, maxChars), truncated: p.text.length > maxChars || undefined, font: { name: p.font?.name ?? '맑은 고딕', size: p.font?.size ?? 11, bold: p.font?.bold ?? false, italic: false, color: p.font?.color ?? '#000000', highlight: p.font?.highlight ?? null, underline: 'None' }, spacing: { before: p.spaceBefore ?? 0, after: p.spaceAfter ?? 8, line: p.lineSpacing ?? 13.8 } })), from, to, total: this.P.length }); }
      case 'read_document': return this.#env({ properties: { ...this.model.properties }, paragraphs: this.P.length, tables: this.model.tables.length, sections: this.model.headers.length, pictures: this.P.filter((p) => p.image).length, comment_threads: this.model.comments.length, headers_footers: this.model.headers.map((h, i) => ({ section: i + 1, ...h })), track_changes: this.model.trackChanges, word_api: 'fake' });
      case 'find': { const text = String(need(a, 'text')); const limit = int(a, 'limit') ?? 50; const mc = bool(a, 'match_case') ?? false; const hits = []; let matched = 0;
        this.P.forEach((p, i) => { const hay = mc ? p.text : p.text.toLowerCase(); const nd = mc ? text : text.toLowerCase(); let at = hay.indexOf(nd); while (at >= 0) { matched += 1; if (hits.length < limit) hits.push({ paragraph: i + 1, text: p.text.slice(at, at + text.length), context: clip(p.text.slice(Math.max(0, at - 30), at + text.length + 30), 100) }); at = hay.indexOf(nd, at + nd.length); } });
        return this.#env({ hits, matched, truncated: matched > hits.length }); }
      case 'read_table': { const { t, n } = this.#table(a); const maxRows = int(a, 'max_rows') ?? 200; return this.#env({ table: n, rows: t.values.length, columns: t.values[0]?.length ?? 0, has_header: t.hasHeader !== false, style: t.style ?? null, align: t.align ?? 'Left', values: t.values.slice(0, maxRows), truncated: t.values.length > maxRows }); }
      case 'read_html': { const { from, to, list } = this.#pick(a, { must: false }); const html = list.map((p) => { const tag = /^Heading (\d)/.exec(p.style ?? '') ? `h${/^Heading (\d)/.exec(p.style)[1]}` : p.style === 'Title' ? 'h1' : 'p'; const inner = p.font?.bold ? `<b>${p.text}</b>` : p.text; return `<${tag}>${inner}</${tag}>`; }).join('\n'); const maxChars = int(a, 'max_chars') ?? 20000; return this.#env({ from, to, html: html.slice(0, maxChars), truncated: html.length > maxChars }); }
      case 'read_comments': { this.#need('WordApi', '1.4', 'read_comments'); const { from, to } = this.#pick(a, { must: false }); const cs = this.model.comments.filter((c) => c.paragraph >= from && c.paragraph <= to); return this.#env({ from, to, count: cs.length, comments: cs.map((c) => ({ id: c.id, author: c.author, date: c.date, on: clip(c.on, 80), text: c.text, resolved: c.resolved, replies: c.replies })) }); }
      case 'read_tracked_changes': { this.#need('WordApi', '1.6', 'read_tracked_changes'); return this.#env({ mode: this.model.trackChanges, count: this.model.changes.length, changes: this.model.changes.slice(0, int(a, 'limit') ?? 100) }); }
      case 'describe_style': { const counts = {}; const headings = []; this.P.forEach((p, i) => { const s = p.style ?? 'Normal'; counts[s] = (counts[s] ?? 0) + 1; if (/^Heading|^Title/.test(s) && headings.length < 12) headings.push({ paragraph: i + 1, style: s, text: clip(p.text, 60) }); });
        return this.#env({ styles: counts, body_font: { name: '맑은 고딕', size: 11, color: '#000000' }, heading_font: { name: '맑은 고딕', size: 16, bold: true, color: '#2F5496' }, headings, paragraphs: this.P.length }); }
      case 'snapshot_paragraphs': { const { from, to, list } = this.#pick(a, { must: false }); const id = `snap-${this.snapshots.size + 1}-${Math.random().toString(36).slice(2, 6)}`; this.snapshots.set(id, { from, to, paragraphs: structuredClone(list) }); return this.#env({ snapshot: id, from, to, paragraphs: list.length }); }
      case 'read_tags': { const tags = Object.entries(this.model.tags).map(([key, value]) => ({ key, value })); return this.#env({ tags, count: tags.length }); }
      case 'read_suggestions': { this.#need('WordApi', '1.4', 'read_suggestions'); const out = Object.entries(this.model.settings).filter(([k]) => k.startsWith(FIX_PREFIX)).map(([k, v]) => FakeHand.decode(k, v)); return this.#env({ scope: 'document', count: out.length, suggestions: out }); }
      case 'advise': return this.#env({ pinned: Array.isArray(a.items) ? a.items.length : 0 });
      case 'clear_advice': return this.#env({ pinned: 0 });

      case 'insert_paragraphs': { const lines = arr(a, 'lines'); if (!lines || !lines.length) refuse('lines 가 비었습니다 — 문단마다 한 줄인 문자열 배열'); const style = str(a, 'style'); const { index, said } = this.#anchor(a);
        const made = lines.map((l) => ({ text: String(l ?? ''), style: style ?? 'Normal' })); this.P.splice(index, 0, ...made); this.#shift(index + 1, made.length); this.#mutated();
        return this.#env({ inserted: made.length, from: index + 1, to: index + made.length, style: style ?? null }, [`${said} 문단 ${made.length}개를 넣었습니다${style ? ` (${style})` : ''} — 문단 ${index + 1}${made.length > 1 ? `–${index + made.length}` : ''}`]); }
      case 'replace_paragraph': { const n = int(a, 'paragraph') ?? int(a, 'para') ?? refuse('paragraph 가 없습니다'); const text = String(a.text ?? a.content ?? refuse('text 가 없습니다')); if (n < 1 || n > this.P.length) refuse(`문서에 ${n}번 문단이 없습니다 — 문단 ${this.P.length}개`); const before = this.P[n - 1].text; this.P[n - 1] = { ...this.P[n - 1], text, font: undefined }; this.#mutated(); return this.#env({ paragraph: n, before: clip(before, 80), after: clip(text, 80) }, [`문단 ${n}: 「${clip(before, 40)}」 → 「${clip(text, 40)}」`]); }
      case 'delete_paragraphs': { const { from, to, list } = this.#pick(a); if (list.length >= this.P.length) refuse('본문의 문단을 전부 지울 수는 없습니다 — 하나는 남겨야 합니다'); this.P.splice(from - 1, list.length); this.#shift(from, -list.length); this.#mutated(); return this.#env({ from, to, deleted: list.length }, [`문단 ${from}${to > from ? `–${to}` : ''} 을 지웠습니다 (${list.length}개) — 되돌릴 수 없습니다`]); }
      case 'set_style': { const style = str(a, 'style'); const builtin = str(a, 'builtin'); if (!style && !builtin) refuse('style 이나 builtin 이 있어야 합니다 — 예: builtin "Heading2"'); const { from, to, list } = this.#pick(a); const name = builtin ? builtin.replace(/^Heading(\d)$/, 'Heading $1') : style; for (const p of list) p.style = name; this.#mutated(); return this.#env({ from, to, style: builtin ?? style }, [`문단 ${from}${to > from ? `–${to}` : ''} 에 스타일 「${builtin ?? style}」`]); }
      case 'format_text': { const b = bool(a, 'bold'); const i = bool(a, 'italic'); const s = bool(a, 'strike'); const u = str(a, 'underline'); const size = num(a, 'size'); const color = hex(a, 'color') ?? hex(a, 'font_color'); const hl = str(a, 'highlight'); const font = str(a, 'font'); const clear = bool(a, 'clear');
        const words = [b != null && (b ? '굵게' : '굵게 해제'), i != null && '기울임', s != null && '취소선', u && `밑줄 ${u}`, size != null && `크기 ${size}`, color && `색 ${color}`, hl && `형광 ${hl}`, font && `글꼴 ${font}`, clear && '직접 서식 지움'].filter(Boolean); if (!words.length) refuse('바꿀 것이 없습니다 — bold·italic·underline·strike·size·color·highlight·font·clear 중 하나');
        const { hits, said } = this.#targets(a); for (const h of hits) { h.p.font = { ...(clear ? {} : h.p.font), ...(b != null ? { bold: b } : {}), ...(size != null ? { size } : {}), ...(color ? { color } : {}), ...(hl ? { highlight: hl === 'none' ? null : hl } : {}), ...(font ? { name: font } : {}) }; } this.#mutated();
        return this.#env({ targets: hits.length }, [`${said}: ${words.join(', ')}`]); }
      case 'format_paragraph': { const align = str(a, 'align'); const sb = num(a, 'space_before'); const sa = num(a, 'space_after'); const ls = num(a, 'line_spacing'); const words = [align && `정렬 ${align}`, sb != null && `앞 ${sb}pt`, sa != null && `뒤 ${sa}pt`, ls != null && `줄 간격 ${ls}pt`, num(a, 'first_line_indent') != null && '첫 줄 들여쓰기', num(a, 'left_indent') != null && '왼쪽 들여쓰기'].filter(Boolean); if (!words.length) refuse('바꿀 것이 없습니다 — align·space_before·space_after·line_spacing·first_line_indent·left_indent·right_indent 중 하나');
        const { from, to, list } = this.#pick(a); for (const p of list) { if (align) p.align = align; if (sb != null) p.spaceBefore = sb; if (sa != null) p.spaceAfter = sa; if (ls != null) p.lineSpacing = ls; } this.#mutated(); return this.#env({ from, to }, [`문단 ${from}${to > from ? `–${to}` : ''}: ${words.join(', ')}`]); }
      case 'insert_table': { const values = arr(a, 'values'); if (!values || !values.length || !values.every((r) => Array.isArray(r))) refuse('values 는 줄마다 배열인 2차원 배열이어야 합니다'); const cols = Math.max(...values.map((r) => r.length)); const rows = values.map((r) => [...r.map((v) => String(v ?? '')), ...Array(cols - r.length).fill('')]); const { index, said } = this.#anchor(a); const t = { after: index, hasHeader: bool(a, 'has_header') ?? true, style: str(a, 'table_style') ?? null, values: rows }; this.model.tables.push(t); this.#mutated(); const n = [...this.model.tables].sort((x, y) => x.after - y.after).indexOf(t) + 1; return this.#env({ table: n, rows: rows.length, columns: cols, has_header: t.hasHeader, style: t.style }, [`${said} ${rows.length}×${cols} 표를 넣었습니다 — 표 ${n}${t.style ? ` (${t.style})` : ''}`]); }
      case 'set_table_cells': { const cells = arr(a, 'cells'); if (!cells || !cells.length) refuse('cells 가 비었습니다 — [{row, column, value}]'); const { t, n } = this.#table(a); for (const c of cells) { const r = int(c, 'row'); const col = int(c, 'column') ?? int(c, 'col'); if (r == null || col == null || r < 0 || col < 0 || r >= t.values.length || col >= t.values[0].length) refuse(`표 밖의 칸입니다 — ${JSON.stringify(c)} (표는 ${t.values.length}×${t.values[0].length}, 0부터)`); t.values[r][col] = String(c.value ?? ''); } this.#mutated(); return this.#env({ table: n, written: cells.length }, [`표 ${n} 의 칸 ${cells.length}개를 적었습니다`]); }
      case 'add_table_rows': { const rows = arr(a, 'rows'); if (!rows || !rows.length || !rows.every((r) => Array.isArray(r))) refuse('rows 는 줄마다 배열인 2차원 배열이어야 합니다'); const { t, n } = this.#table(a); const cols = t.values[0].length; const padded = rows.map((r) => [...r.map((v) => String(v ?? '')), ...Array(Math.max(0, cols - r.length)).fill('')].slice(0, cols)); const at = str(a, 'at') === 'start' ? 'Start' : 'End'; if (at === 'End') t.values.push(...padded); else t.values.splice(t.hasHeader ? 1 : 0, 0, ...padded); this.#mutated(); return this.#env({ table: n, added: padded.length, rows: t.values.length }, [`표 ${n} ${at === 'End' ? '끝' : '앞'}에 행 ${padded.length}개를 넣었습니다`]); }
      case 'delete_table': { const { t, n } = this.#table(a); const rows = t.values.length; this.model.tables.splice(this.model.tables.indexOf(t), 1); this.#mutated(); return this.#env({ table: n, rows }, [`표 ${n} (${rows}행)을 지웠습니다 — 되돌릴 수 없습니다`]); }
      case 'format_table_cells': {
        const { t, n } = this.#table(a); const rows = t.values.length; const cols = t.values[0]?.length ?? 0;
        const fill = hex(a, 'fill', true); const color = hex(a, 'color'); const b = bool(a, 'bold'); const i = bool(a, 'italic'); const size = num(a, 'size'); const align = str(a, 'align'); const valign = str(a, 'valign'); const width = num(a, 'width');
        const words = [fill && `채우기 ${fill}`, color && `글자색 ${color}`, b != null && (b ? '굵게' : '굵게 해제'), i != null && (i ? '기울임' : '기울임 해제'), size != null && `크기 ${size}`, align && `가로 ${align}`, valign && `세로 ${valign}`, width != null && `너비 ${width}pt`].filter(Boolean);
        if (!words.length) refuse('바꿀 것이 없습니다 — fill·color·bold·italic·size·align·valign·width 중 하나');
        const span = (v, max, what) => { if (v == null) return [0, max - 1]; const ar = Array.isArray(v) ? v : [v]; const lo = int({ v: ar[0] }, 'v') ?? 0; const hi = int({ v: ar[1] ?? ar[0] }, 'v') ?? lo; if (lo < 0 || hi >= max || lo > hi) refuse(`${what} 범위가 표 밖입니다 — ${JSON.stringify(v)} (0부터 ${max - 1}까지)`); return [lo, hi]; };
        const cells = arr(a, 'cells'); let targets;
        if (cells && cells.length) targets = cells.map((c) => { const r = int(c, 'row'); const col = int(c, 'column') ?? int(c, 'col'); if (r == null || col == null || r < 0 || col < 0 || r >= rows || col >= cols) refuse(`표 밖의 칸입니다 — ${JSON.stringify(c)} (표는 ${rows}×${cols}, 0부터)`); return [r, col]; });
        else { const [r0, r1] = span(a.rows, rows, 'rows'); const [c0, c1] = span(a.columns, cols, 'columns'); targets = []; for (let r = r0; r <= r1; r += 1) for (let c = c0; c <= c1; c += 1) targets.push([r, c]); }
        t.cellFmt ??= {}; for (const [r, c] of targets) t.cellFmt[`${r},${c}`] = { ...(t.cellFmt[`${r},${c}`] ?? {}), fill, color, bold: b, italic: i, size, align, valign, width };
        this.#mutated(); return this.#env({ table: n, cells: targets.length }, [`표 ${n} 의 칸 ${targets.length}개: ${words.join(', ')}`]);
      }
      case 'edit_table': {
        const delRows = arr(a, 'delete_rows'); const delCols = arr(a, 'delete_columns'); const add = a.add_columns && typeof a.add_columns === 'object' ? a.add_columns : null; const merge = a.merge && typeof a.merge === 'object' ? a.merge : null;
        if (!delRows?.length && !delCols?.length && !add && !merge) refuse('할 일이 없습니다 — delete_rows·delete_columns·add_columns·merge 중 하나');
        if (merge) this.#need('WordApi', '1.4', 'edit_table{merge}');
        const { t, n } = this.#table(a); const done = [];
        if (merge) { const fr = int(merge, 'from_row') ?? 0; const fc = int(merge, 'from_column') ?? 0; const tr = int(merge, 'to_row') ?? fr; const tc = int(merge, 'to_column') ?? fc; if (fr < 0 || fc < 0 || tr >= t.values.length || tc >= t.values[0].length || fr > tr || fc > tc) refuse(`merge 가 표 밖입니다 — ${JSON.stringify(merge)}`); (t.merges ??= []).push([fr, fc, tr, tc]); done.push(`(${fr},${fc})–(${tr},${tc}) 병합`); }
        if (add) { const count = int(add, 'count') ?? (Array.isArray(add.values) ? add.values.length : 1); const values = Array.isArray(add.values) ? add.values : []; const at = add.at ?? 'end'; const cols = t.values[0].length; let pos = at === 'end' ? cols : at === 'start' ? 0 : (int({ v: at }, 'v') ?? -1) + 1; if (pos < 0 || pos > cols) refuse(`add_columns.at 이 표 밖입니다 — ${at}`); t.values.forEach((row, r) => { row.splice(pos, 0, ...Array.from({ length: count }, (_, k) => String(values[k]?.[r] ?? ''))); }); done.push(`열 ${count}개 추가(${at})`); }
        if (delCols?.length) { const idxs = [...new Set(delCols.map((v) => int({ v }, 'v')))].sort((x, y) => y - x); for (const c of idxs) { if (c == null || c < 0 || c >= t.values[0].length) refuse(`delete_columns 가 표 밖입니다 — ${c}`); t.values.forEach((row) => row.splice(c, 1)); } done.push(`열 ${idxs.length}개 삭제`); }
        if (delRows?.length) { const idxs = [...new Set(delRows.map((v) => int({ v }, 'v')))].sort((x, y) => y - x); for (const r of idxs) { if (r == null || r < 0 || r >= t.values.length) refuse(`delete_rows 가 표 밖입니다 — ${r}`); t.values.splice(r, 1); } done.push(`행 ${idxs.length}개 삭제`); }
        this.#mutated(); return this.#env({ table: n, rows: t.values.length, columns: t.values[0]?.length ?? 0 }, [`표 ${n}: ${done.join(', ')} — 이제 ${t.values.length}×${t.values[0]?.length ?? 0}`]);
      }
      case 'format_table': { const style = str(a, 'table_style'); const header = bool(a, 'header_row'); const align = str(a, 'align'); const widths = arr(a, 'widths'); const words = [style && `스타일 ${style}`, header != null && (header ? '머리글 행' : '머리글 행 해제'), bool(a, 'banded_rows') != null && '줄무늬 행', bool(a, 'banded_columns') != null && '줄무늬 열', align && `정렬 ${align}`, widths && `열 너비 ${widths.join('/')}`].filter(Boolean); if (!words.length) refuse('바꿀 것이 없습니다 — table_style·header_row·banded_rows·banded_columns·align·widths 중 하나'); const { t, n } = this.#table(a); if (style) t.style = style; if (header != null) t.hasHeader = header; if (align) t.align = align; if (widths) t.widths = widths; this.#mutated(); return this.#env({ table: n }, [`표 ${n}: ${words.join(', ')}`]); }
      case 'insert_list': { const items = arr(a, 'items'); if (!items || !items.length) refuse('items 가 비었습니다'); const kind = str(a, 'kind') ?? 'bulleted'; const levels = arr(a, 'levels') ?? []; const { index, said } = this.#anchor(a); const made = items.map((t, i) => ({ text: String(t), style: 'List Paragraph', list: { kind, level: Number(levels[i] ?? 0) || 0 } })); this.P.splice(index, 0, ...made); this.#shift(index + 1, made.length); this.#mutated(); return this.#env({ inserted: made.length, kind, from: index + 1, to: index + made.length }, [`${said} ${kind === 'numbered' ? '번호' : '글머리 기호'} 목록 ${made.length}개를 넣었습니다`]); }
      case 'set_list': { const kind = str(a, 'kind'); const level = int(a, 'level'); const detach = bool(a, 'detach') ?? false; if (!kind && level == null && !detach) refuse('kind·level·detach 중 하나가 있어야 합니다'); const { from, to, list } = this.#pick(a); for (const p of list) { if (detach) { delete p.list; p.style = 'Normal'; } else { p.list = { kind: kind ?? p.list?.kind ?? 'bulleted', level: level ?? p.list?.level ?? 0 }; p.style = 'List Paragraph'; } } this.#mutated(); return this.#env({ from, to, kind: kind ?? null, level: level ?? null, detached: detach }, [detach ? `문단 ${from}${to > from ? `–${to}` : ''} 을 목록에서 뺐습니다` : `문단 ${from}${to > from ? `–${to}` : ''} 을 ${kind === 'numbered' ? '번호 ' : kind === 'bulleted' ? '글머리 기호 ' : ''}목록으로${level != null ? ` (단계 ${level})` : ''}`]); }
      case 'insert_image': { const b64 = str(a, 'image_base64'); if (!b64) refuse('그림 바이트가 안 왔습니다 — path 를 주면 헬퍼가 읽어 실어 줍니다'); const { index, said } = this.#anchor(a); const w = num(a, 'width') ?? 200; this.P.splice(index, 0, { text: '', style: 'Normal', image: { width: w, height: Math.round(w * 0.6), alt: str(a, 'alt') ?? '' } }); this.#shift(index + 1, 1); this.#mutated(); return this.#env({ width: w, height: Math.round(w * 0.6) }, [`${said} 그림을 넣었습니다 (${w}×${Math.round(w * 0.6)}pt)`]); }
      case 'set_style_format': {
        this.#need('WordApi', '1.5', 'set_style_format');
        const given = String(need(a, 'style')); const create = bool(a, 'create') ?? false;
        const fmt = { font: str(a, 'font'), size: num(a, 'size'), bold: bool(a, 'bold'), italic: bool(a, 'italic'), color: hex(a, 'color'), align: str(a, 'align'), space_before: num(a, 'space_before'), space_after: num(a, 'space_after'), line_spacing: num(a, 'line_spacing'), first_line_indent: num(a, 'first_line_indent'), left_indent: num(a, 'left_indent') };
        const set = Object.entries(fmt).filter(([, v]) => v != null);
        if (set.length === 0) refuse('바꿀 것이 없습니다 — font·size·bold·italic·color·align·space_before·space_after·line_spacing·first_line_indent·left_indent 중 하나');
        const norm = (s) => String(s).replace(/[\s_-]/g, '').toLowerCase();
        const known = new Set([...this.P.map((p) => p.style ?? 'Normal'), ...Object.keys(this.model.styleDefs), 'Normal', 'Heading 1', 'Heading 2', 'Heading 3', 'Title']);
        let local = [...known].find((s) => s === given) ?? [...known].find((s) => norm(s) === norm(given));
        if (!local && create) local = given;
        if (!local) refuse(`「${given}」 스타일이 없습니다 — 이 문서의 스타일: ${[...known].join(', ')}. 새로 만들려면 create: true`);
        this.model.styleDefs[local] = { ...(this.model.styleDefs[local] ?? {}), ...Object.fromEntries(set) };
        const affected = this.P.filter((p) => (p.style ?? 'Normal') === local).length; this.#mutated();
        return this.#env({ style: local, builtin: BUILTIN_PARAGRAPH_STYLES.find((b) => b.toLowerCase() === norm(given)) ?? null, affected, created: !known.has(local) }, [`스타일 「${local}」: ${set.map(([k, v]) => `${k} ${v}`).join(', ')} — 문단 ${affected}개에 걸립니다`]);
      }
      case 'read_footnotes': { this.#need('WordApi', '1.5', 'read_footnotes'); const { from, to } = this.#pick(a, { must: false }); const out = []; for (const kind of ['footnote', 'endnote']) this.model.notes.filter((n) => n.kind === kind).forEach((n, i) => { if (n.paragraph >= from && n.paragraph <= to) out.push({ number: i + 1, kind, paragraph: n.paragraph, on: clip(n.on, 60), text: clip(n.text, 200) }); }); return this.#env({ from, to, count: out.length, notes: out }); }
      case 'insert_footnote': { this.#need('WordApi', '1.5', 'insert_footnote'); const note = String(need(a, 'note')); const kind = str(a, 'kind') ?? 'footnote'; const n = int(a, 'paragraph') ?? int(a, 'from') ?? refuse('paragraph 가 없습니다 — 각주가 걸릴 문단 번호'); const { hits, said } = this.#targets({ ...a, from: n, to: n }); this.model.notes.push({ kind, paragraph: hits[0].i, on: str(a, 'text') ?? hits[0].p.text, text: note }); this.#mutated(); return this.#env({ paragraph: hits[0].i, kind, number: this.model.notes.filter((n) => n.kind === kind).length }, [`${said} 에 ${kind === 'endnote' ? '미주' : '각주'}를 달았습니다 — 「${clip(note, 40)}」`]); }
      case 'delete_footnote': { this.#need('WordApi', '1.5', 'delete_footnote'); const number = int(a, 'number') ?? refuse('number 가 없습니다 — read_footnotes 의 번호'); const kind = str(a, 'kind') ?? 'footnote'; const mine = this.model.notes.filter((n) => n.kind === kind); if (number < 1 || number > mine.length) refuse(`${kind === 'endnote' ? '미주' : '각주'} ${number}번이 없습니다 — ${mine.length}개`); this.model.notes.splice(this.model.notes.indexOf(mine[number - 1]), 1); this.#mutated(); return this.#env({ number, kind, deleted: true }, [`${kind === 'endnote' ? '미주' : '각주'} ${number}번을 지웠습니다 — 글은 그대로입니다`]); }
      case 'list_images': { const { from, to } = this.#pick(a, { must: false }); const images = []; this.P.forEach((p, i) => { if (p.image && i + 1 >= from && i + 1 <= to) images.push({ number: this.P.slice(0, i + 1).filter((q) => q.image).length, paragraph: i + 1, width: Math.round(p.image.width), height: Math.round(p.image.height), alt: p.image.alt ?? '' }); }); return this.#env({ from, to, count: images.length, images }); }
      case 'format_image': { const n = int(a, 'image') ?? refuse('image 가 없습니다 — list_images 의 번호'); const w = num(a, 'width'); const h = num(a, 'height'); const alt = str(a, 'alt'); const align = str(a, 'align'); const words = [w != null && `너비 ${w}pt`, h != null && `높이 ${h}pt`, alt != null && `대체 텍스트 「${clip(alt, 30)}」`, align && `정렬 ${align}`].filter(Boolean); if (!words.length) refuse('바꿀 것이 없습니다 — width·height·alt·align 중 하나'); const pics = this.P.filter((p) => p.image); if (n < 1 || n > pics.length) refuse(`그림 ${n}번이 없습니다 — 그림 ${pics.length}개`); const p = pics[n - 1]; const ratio = p.image.height / p.image.width; if (w != null && h != null) { p.image.width = w; p.image.height = h; } else if (w != null) { p.image.width = w; p.image.height = Math.round(w * ratio); } else if (h != null) { p.image.height = h; p.image.width = Math.round(h / ratio); } if (alt != null) p.image.alt = alt; if (align) p.align = align; this.#mutated(); return this.#env({ image: n, width: Math.round(p.image.width), height: Math.round(p.image.height) }, [`그림 ${n}: ${words.join(', ')} (지금 ${Math.round(p.image.width)}×${Math.round(p.image.height)}pt)`]); }
      case 'delete_image': { const n = int(a, 'image') ?? refuse('image 가 없습니다 — list_images 의 번호'); const pics = this.P.filter((p) => p.image); if (n < 1 || n > pics.length) refuse(`그림 ${n}번이 없습니다 — 그림 ${pics.length}개`); delete pics[n - 1].image; this.#mutated(); return this.#env({ image: n, deleted: true }, [`그림 ${n}번을 지웠습니다 — 문단은 그대로입니다`]); }
      case 'insert_field': {
        this.#need('WordApi', '1.5', 'insert_field');
        const { pieces, said: what } = fieldPieces(a);
        const sample = { toc: '[목차]', page: '1', pages: '1', num_pages: '1', date: '2026-09-06', time: '12:00', title: this.model.properties?.title ?? '', author: this.model.properties?.author ?? '', file: 'doc.docx', file_name: 'doc.docx' };
        const text = pieces.map((p) => (p.text != null ? p.text : sample[p.name])).join('');
        const which = str(a, 'which');
        if (which) {
          const section = int(a, 'section') ?? 1; if (section < 1 || section > this.model.headers.length) refuse(`문서에 ${section}번 구역이 없습니다 — 구역 ${this.model.headers.length}개`);
          const h = this.model.headers[section - 1]; h[which] = h[which] ? `${h[which]}\n${text}` : text; this.#mutated();
          return this.#env({ fields: pieces.filter((p) => p.type).length, which }, [`구역 ${section} ${which === 'header' ? '머리글' : '바닥글'}(${str(a, 'kind') ?? 'Primary'})에 ${what}`]);
        }
        const { index, said } = this.#anchor(a);
        this.P.splice(index, 0, { text, style: 'Normal', align: str(a, 'align') ?? undefined, field: pieces.filter((p) => p.type).map((p) => p.name) }); this.#shift(index + 1, 1);
        this.#mutated();
        return this.#env({ fields: pieces.filter((p) => p.type).length, which: null, paragraph: index + 1 }, [`${said} ${what}`]);
      }
      case 'insert_break': { const n = int(a, 'paragraph') ?? int(a, 'para') ?? refuse('paragraph 가 없습니다'); const kind = str(a, 'kind') ?? 'page'; if (!['page', 'section', 'line'].includes(kind)) refuse(`kind 는 page·section·line 중 하나 — ${kind}`); if (n < 1 || n > this.P.length) refuse(`문서에 ${n}번 문단이 없습니다 — 문단 ${this.P.length}개`); this.P[n - 1].breakAfter = kind; if (kind === 'section') this.model.headers.push({ header: '', footer: '' }); this.#mutated(); return this.#env({ paragraph: n, kind }, [`문단 ${n} 뒤에 ${{ page: '쪽', section: '구역', line: '줄' }[kind]} 나누기`]); }
      case 'set_header_footer': { const which = str(a, 'which') ?? refuse('which 가 없습니다 — header 나 footer'); const text = String(a.text ?? refuse('text 가 없습니다')); const section = int(a, 'section') ?? 1; if (section < 1 || section > this.model.headers.length) refuse(`문서에 ${section}번 구역이 없습니다 — 구역 ${this.model.headers.length}개`); this.model.headers[section - 1][which] = text; this.#mutated(); return this.#env({ which, section, kind: str(a, 'kind') ?? 'Primary', text }, [`구역 ${section} ${which === 'header' ? '머리글' : '바닥글'}(${str(a, 'kind') ?? 'Primary'}) → 「${clip(text, 40)}」`]); }
      case 'set_hyperlink': { const url = str(a, 'url'); const { hits, said } = this.#targets(a); for (const h of hits) h.p.link = url ?? null; this.#mutated(); return this.#env({ targets: hits.length, url: url ?? null }, [url ? `${said} 에 링크 → ${url}` : `${said} 의 링크를 뗐습니다`]); }
      case 'replace_all': { const find = String(need(a, 'find')); const replace = String(a.replace ?? refuse('replace 가 없습니다(빈 문자열은 됩니다)')); const limit = int(a, 'limit'); const mc = bool(a, 'match_case') ?? false; const { from, to, list } = this.#pick(a, { must: false }); let n = 0; const where = new Set();
        list.forEach((p, i) => { const re = new RegExp(find.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), mc ? 'g' : 'gi'); p.text = p.text.replace(re, (m) => { if (limit != null && n >= limit) return m; n += 1; where.add(from + i); return replace; }); });
        if (n === 0) refuse(`「${clip(find, 40)}」 가 문단 ${from}–${to} 에 없습니다`); this.#mutated(); return this.#env({ replaced: n, paragraphs: [...where] }, [`「${clip(find, 30)}」 → 「${clip(replace, 30)}」 ${n}곳 (문단 ${[...where].slice(0, 8).join(', ')})`]); }
      case 'add_comment': { this.#need('WordApi', '1.4', 'add_comment'); const comment = String(need(a, 'comment')); const { hits, said } = this.#targets(a); const id = String(this.nextComment++); this.model.comments.push({ id, paragraph: hits[0].i, on: str(a, 'text') ?? hits[0].p.text, text: comment, author: 'magi', date: new Date().toISOString(), resolved: false, replies: [] }); this.#mutated(); return this.#env({ id, on: said }, [`${said} 에 메모를 달았습니다 — 「${clip(comment, 40)}」`]); }
      case 'reply_comment': { this.#need('WordApi', '1.4', 'reply_comment'); const id = String(need(a, 'id')); const c = this.model.comments.find((x) => x.id === id) ?? refuse(`id ${id} 인 메모가 없습니다 — read_comments 가 id 를 줍니다`); c.replies.push({ author: 'magi', date: new Date().toISOString(), text: String(need(a, 'text')) }); this.#mutated(); return this.#env({ id }, [`메모 ${id} 에 답글 — 「${clip(String(a.text), 40)}」`]); }
      case 'resolve_comment': { this.#need('WordApi', '1.4', 'resolve_comment'); const id = String(need(a, 'id')); const c = this.model.comments.find((x) => x.id === id) ?? refuse(`id ${id} 인 메모가 없습니다 — read_comments 가 id 를 줍니다`); const del = bool(a, 'delete') ?? false; const resolved = bool(a, 'resolved') ?? true; if (del) this.model.comments.splice(this.model.comments.indexOf(c), 1); else c.resolved = resolved; this.#mutated(); return this.#env({ id, deleted: del, resolved: del ? null : resolved }, [del ? `메모 ${id} 를 지웠습니다` : `메모 ${id} 를 ${resolved ? '해결로' : '미해결로'} 표시했습니다`]); }
      case 'add_bookmark': { this.#need('WordApi', '1.4', 'add_bookmark'); const name = String(need(a, 'name')); if (!/^[A-Za-z][A-Za-z0-9_]{0,39}$/.test(name)) refuse(`책갈피 이름은 영문자로 시작하는 영문·숫자·밑줄 40자 이내 — ${name}`); const { from, to } = this.#pick(a); this.model.bookmarks[name] = { from, to }; this.#mutated(); return this.#env({ name, from, to }, [`문단 ${from}${to > from ? `–${to}` : ''} 에 책갈피 「${name}」`]); }
      case 'delete_bookmark': { this.#need('WordApi', '1.4', 'delete_bookmark'); const name = String(need(a, 'name')); if (!this.model.bookmarks[name]) refuse(`책갈피 「${name}」 가 없습니다`); delete this.model.bookmarks[name]; this.#mutated(); return this.#env({ name }, [`책갈피 「${name}」 를 지웠습니다 — 글은 그대로입니다`]); }
      case 'set_track_changes': { this.#need('WordApi', '1.4', 'set_track_changes'); const mode = str(a, 'mode') ?? refuse('mode 가 없습니다 — Off, TrackAll, TrackMineOnly'); this.model.trackChanges = mode; this.count += 1; return this.#env({ mode }, [`변경 추적 → ${mode}`]); }
      case 'review_changes': { this.#need('WordApi', '1.6', 'review_changes'); const what = str(a, 'what') ?? refuse('what 이 없습니다 — accept 나 reject'); const n = this.model.changes.length; this.model.changes = []; this.count += 1; return this.#env({ what, count: n }, [`변경 ${n}건을 ${what === 'accept' ? '수락' : '거부'}했습니다`]); }
      case 'set_properties': { const keys = ['title', 'subject', 'author', 'keywords', 'comments', 'category'].filter((k) => a[k] != null); if (!keys.length) refuse('바꿀 속성이 없습니다 — title·subject·author·keywords·comments·category'); for (const k of keys) this.model.properties[k] = String(a[k]); this.#mutated(); return this.#env({ set: keys }, [`문서 속성: ${keys.map((k) => `${k}=「${clip(String(a[k]), 30)}」`).join(', ')}`]); }
      case 'restore_paragraphs': { const id = String(need(a, 'snapshot')); const snap = this.snapshots.get(id); if (!snap) refuse(`그런 스냅숏이 없습니다: ${id} — snapshot_paragraphs 가 준 id 를 주세요(이 창이 뜬 뒤 찍은 것만 압니다)`); if (snap.from > this.P.length) refuse(`스냅숏의 자리(문단 ${snap.from})가 지금 문서에 없습니다 — 문단 ${this.P.length}개`); const n = Math.min(snap.to, this.P.length) - snap.from + 1; this.P.splice(snap.from - 1, n, ...structuredClone(snap.paragraphs)); this.#shift(snap.from, snap.paragraphs.length - n); this.#mutated(); return this.#env({ snapshot: id, from: snap.from, to: snap.to }, [`문단 ${snap.from}–${snap.to} 을 스냅숏 ${id} 로 되돌렸습니다`]); }
      case 'set_tag': { const key = String(need(a, 'key')); const value = String(a.value ?? ''); if (key.startsWith(FIX_PREFIX) || key === DOC_PROPERTY_KEY) refuse('그 키는 제안·문서 이름의 것이라 기록으로 못 씁니다'); if (value.length > 255) refuse(`Word 의 사용자 지정 속성은 255자까지입니다 — ${value.length}자`); const k = key.startsWith('MAGI.') ? key : `MAGI.${key}`; if (value === '') delete this.model.tags[k]; else this.model.tags[k] = value; this.#mutated(); return this.#env({ key: k, value }, [value === '' ? `기록 '${k}' 를 지웠습니다` : `기록 '${k}' 를 남겼습니다 — 「${clip(value, 40)}」`]); }
      case 'suggest': { this.#need('WordApi', '1.4', 'suggest'); const what = String(need(a, 'what')); const fix = a.fix && typeof a.fix === 'object' ? a.fix : null; if (fix && !FIX_TOOLS.includes(String(fix.tool))) refuse(`제안으로 누를 수 있는 손은 ${FIX_TOOLS.join(', ')} 뿐입니다 — ${fix.tool}`); const key = `${FIX_PREFIX}${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2, 6).toUpperCase()}`; this.model.settings[key] = JSON.stringify({ what, why: str(a, 'why') ?? '', paragraph: int(a, 'paragraph'), fix }); this.#mutated(); return this.#env({ suggestion: key, paragraph: int(a, 'paragraph') }, [`${int(a, 'paragraph') ? `문단 ${int(a, 'paragraph')} 에` : '문서에'} 제안을 붙였습니다 — ${clip(what, 60)}. **이건 아직 안 고친 것입니다** — 작업창의 「적용」을 누르기 전까지 문서는 그대로입니다`]); }
      case 'drop_suggestion': { this.#need('WordApi', '1.4', 'drop_suggestion'); const key = String(need(a, 'key')); if (!key.startsWith(FIX_PREFIX)) refuse(`제안의 키가 아닙니다 — ${key}`); if (!(key in this.model.settings)) refuse(`그런 제안이 없습니다: ${key}`); delete this.model.settings[key]; this.#mutated(); return this.#env({ key }, [`제안 ${key} 를 뗐습니다 — 고치지는 않았습니다`]); }
      default: refuse(`아직 손이 없는 조작입니다: ${op}`);
    }
  }
  static decode(key, value) {
    let body = null; try { body = typeof value === 'string' ? JSON.parse(value) : value; } catch { body = null; }
    if (!body || typeof body !== 'object' || typeof body.what !== 'string') return { key, what: '읽을 수 없는 제안입니다', broken: true, appliable: false };
    const fix = body.fix && typeof body.fix === 'object' && body.fix.tool ? body.fix : null;
    return { key, what: body.what, why: body.why ?? '', paragraph: body.paragraph ?? null, fix, appliable: Boolean(fix && FIX_TOOLS.includes(fix.tool)) };
  }
}
