//go:build ignore

// Bake the icons the page asks for into a sprite this binary carries.
//
// # Why a generator and not files in the repository
//
// The icons are Font Awesome Pro. Their licence permits using them in something you deploy and
// does not permit republishing them as files, so they cannot live in a public repository — and a
// CDN is not an option either: this console is read over ssh into machines that have no route to
// the internet, and it must not tell a third party which workspace is being looked at.
//
// So the art arrives at BUILD time and the repository holds only the names. Run:
//
//	MAGI_FA_DIR=~/Downloads/kit-…-web go generate ./cmd/magi-web
//
// or, in CI, point it at the Pro package restored from the registry with a token:
//
//	MAGI_FA_DIR=node_modules/@fortawesome/fontawesome-pro go generate ./cmd/magi-web
//
// Both layouts are the same — svgs/<style>/<name>.svg — which is why there is one reader here
// rather than one per source.
//
// # What it emits, and what happens without it
//
// icons_gen.go, which is git-ignored, and which sets iconSprite in an init. Without it iconSprite
// stays empty, the page draws the shapes it has always drawn, and nothing is broken: a build with
// no licence produces a working console with plainer icons. The test suite runs both ways.
//
// # Which icons
//
// The ones the page NAMES. Every reference is written <use href="#i-<style>-<icon>">, so the page
// itself is the list — a manifest kept beside it would be a second place to edit and the place
// where an icon goes missing.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// styleDir maps the prefix used in an id to the directory it comes from. Short, because it is
// typed into every reference in the page: sl = sharp light, ss = sharp solid, b = brands.
var styleDir = map[string]string{
	"sl": "sharp-light",
	"ss": "sharp-solid",
	"b":  "brands",
}

func main() {
	root := os.Getenv("MAGI_FA_DIR")
	if root == "" {
		fmt.Fprintln(os.Stderr, "gen_icons: MAGI_FA_DIR is not set — no sprite written, the page will draw its own shapes")
		return
	}
	// The two files that can name an icon. The stylesheet cannot: an id in CSS would be a reference
	// nothing renders.
	var srcs []string
	for _, f := range []string{"page.html", "page.js"} {
		b, err := os.ReadFile(f)
		if err != nil {
			die(err)
		}
		srcs = append(srcs, string(b))
	}
	want := map[string]bool{}
	ref := regexp.MustCompile(`#i-(sl|ss|b)-([a-z0-9-]+)`)
	for _, s := range srcs {
		for _, m := range ref.FindAllStringSubmatch(s, -1) {
			want[m[1]+"-"+m[2]] = true
		}
	}
	if len(want) == 0 {
		fmt.Fprintln(os.Stderr, "gen_icons: the page names no icons; nothing to bake")
		return
	}

	names := make([]string, 0, len(want))
	for n := range want {
		names = append(names, n)
	}
	sort.Strings(names)

	var sprite strings.Builder
	// aria-hidden and display:none, because this is a definition block and not a picture: left
	// visible it is a 0×0 svg that still takes a line box, and read out it is a list of nothing.
	sprite.WriteString(`<svg id="isprite" aria-hidden="true" style="display:none">`)
	var missing []string
	for _, n := range names {
		i := strings.Index(n, "-")
		style, icon := n[:i], n[i+1:]
		dir, ok := styleDir[style]
		if !ok {
			die(fmt.Errorf("unknown style prefix in #i-%s", n))
		}
		b, err := os.ReadFile(filepath.Join(root, "svgs", dir, icon+".svg"))
		if err != nil {
			missing = append(missing, n)
			continue
		}
		box, body, err := carve(string(b))
		if err != nil {
			die(fmt.Errorf("%s: %w", n, err))
		}
		fmt.Fprintf(&sprite, `<symbol id="i-%s" viewBox="%s">%s</symbol>`, n, box, body)
	}
	sprite.WriteString(`</svg>`)

	// A named icon with no file is a hole in the page, not a warning to scroll past: the build
	// stops and says which, because the alternative is a screen with a gap where a control was.
	if len(missing) > 0 {
		die(fmt.Errorf("the page asks for icons this download does not have: %s\n"+
			"add them to the kit (or fix the name) and download again", strings.Join(missing, ", ")))
	}

	out := "// Code generated by gen_icons.go. DO NOT EDIT.\n" +
		"// Font Awesome Pro icons, baked in at build time — see gen_icons.go for why this file is\n" +
		"// not in the repository. Font Awesome Pro is licensed to whoever built this binary:\n" +
		"// https://fontawesome.com/license\n\n" +
		"package main\n\n" +
		"func init() { iconSprite = " + quote(sprite.String()) + " }\n"
	// Formatted, because the gate formats everything and a generated file is not exempt from
	// being read: an unformatted one fails the build for a reason that has nothing to do with the
	// change somebody just made.
	pretty, err := format.Source([]byte(out))
	if err != nil {
		die(fmt.Errorf("the generated file does not parse: %w", err))
	}
	if err := os.WriteFile("icons_gen.go", pretty, 0o644); err != nil {
		die(err)
	}
	fmt.Fprintf(os.Stderr, "gen_icons: %d icons baked from %s\n", len(names), root)
}

// carve takes the viewBox and the drawing out of one downloaded file.
//
// The file also carries an xmlns, a width, a licence comment and a fill — none of which belong in
// a symbol: the namespace is the parent svg's, the size is the use site's, and the fill is already
// currentColor. Keeping them would multiply the licence comment by a hundred and put an attribute
// on every shape that the stylesheet then has to fight.
func carve(s string) (box, body string, err error) {
	m := regexp.MustCompile(`viewBox="([^"]+)"`).FindStringSubmatch(s)
	if m == nil {
		return "", "", fmt.Errorf("no viewBox")
	}
	box = m[1]
	i := strings.Index(s, ">")
	j := strings.LastIndex(s, "</svg>")
	if i < 0 || j < 0 || j < i {
		return "", "", fmt.Errorf("not an svg")
	}
	body = s[i+1 : j]
	body = regexp.MustCompile(`(?s)<!--.*?-->`).ReplaceAllString(body, "")
	return box, strings.TrimSpace(body), nil
}

// quote writes a Go string literal. Backquotes are not usable — a path can contain one — and
// %q is exactly right for the rest.
func quote(s string) string { return fmt.Sprintf("%q", s) }

func die(err error) {
	fmt.Fprintln(os.Stderr, "gen_icons:", err)
	os.Exit(1)
}
