import { test } from 'node:test';
import * as assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseDraftArchive, restoreDraftArchive } from '../core/draft_archive';
const cases = JSON.parse(readFileSync(resolve(__dirname, '../../../contract/draft-archive-fixtures.json'), 'utf8'));
for (const c of cases) test(`draft archive shared contract: ${c.name}`, () => {
  if (!c.valid) { assert.throws(() => parseDraftArchive(c.raw, c.workspace)); return; }
  const a = parseDraftArchive(c.raw, c.workspace);
  const before = JSON.stringify(a);
  assert.deepEqual(restoreDraftArchive(a), c.expected);
  assert.equal(JSON.stringify(a), before, 'restore must not mutate the stored snapshot');
  assert.deepEqual(parseDraftArchive(JSON.stringify(a), c.workspace), a);
});

import { createAnswerState } from '../core/answer_state';
test('answer state archives inactive sessions and restores only recoveries without replacing new input', () => {
  const state = createAnswerState();
  state.switchContext('/work', 's1');
  state.onInputChange('general one');
  state.enterAnswerMode('q1', 'question', 'general one');
  state.onInputChange('submitted');
  state.submitReply('q1', 'submitted');
  state.switchContext('/work', 's2');
  state.onInputChange('general two');
  const archive = state.exportArchive('file:///work', 'owner-a', 1);
  assert.ok(archive.entries.some(e => e.sessionId === 's1' && e.text === 'general one'));
  assert.ok(archive.entries.some(e => e.sessionId === 's2' && e.text === 'general two'));
  assert.ok(archive.entries.some(e => e.kind === 'attempt' && e.text === 'submitted'));
  const next = createAnswerState();
  next.switchContext('/work', 's2');
  next.onInputChange('new input');
  next.importArchive(archive, 'file:///work');
  next.importArchive(archive, 'file:///work');
  assert.equal(next.getGeneralDraft(), 'new input');
  assert.equal(next.getPendingQuestion(), null);
  assert.equal(next.isInFlight('q1', '/work', 's1'), false);
  assert.equal(next.listRecoveryItems().length, archive.entries.length);
  const unknown = next.listRecoveryItems().find(e => e.archiveEntry?.status === 'unknown');
  assert.ok(unknown);
  const again = next.exportArchive('file:///work', 'owner-b', 1);
  assert.ok(again.entries.some(e => e.id === unknown.recoveryId && e.status === 'unknown'));
  next.deleteRecoveryItem(unknown.recoveryId);
  next.importArchive(archive, 'file:///work');
  assert.equal(next.getRecoveryItem(unknown.recoveryId), undefined);
  const afterDelete = next.exportArchive('file:///work', 'owner-b', 2);
  const restarted = createAnswerState();
  restarted.importArchive(afterDelete, 'file:///work');
  restarted.importArchive(archive, 'file:///work');
  assert.equal(restarted.getRecoveryItem(unknown.recoveryId), undefined);
});
